### ISSUE TITLE
Support Vuetify

### ISSUE THREAD

**Issue by HamedFathi** [scleriot/vue-inputmask#11]
How to use this with `Vuetify` controls specially  `v-text-field`?

**Comment by meyt** [comment]
Very simple implementation: 

https://gist.github.com/meyt/e05d70c05b4c232bf49f5abd644dc577

![image](https://user-images.githubusercontent.com/10482278/53881611-5bd47d80-4029-11e9-8668-70643009ef83.png)

![image](https://user-images.githubusercontent.com/10482278/53881670-80305a00-4029-11e9-80a8-7ba9d80237e4.png)

**Comment by Mirkadoi** [comment]
https://github.com/scleriot/vue-inputmask/issues/6#issuecomment-389458116

**Comment by HamedFathi** [comment]
@Mirkadoi Thanks :)
