### ISSUE TITLE
Multiple masks

### ISSUE THREAD

**Issue by mariuszniemiec** [scleriot/vue-inputmask#13]
Hi
I have trouble to make it work with multi mask.
My input looks like:
`<input type="tel"  name="phone" v-model.trim="form.phone" v-mask="phoneMask">`
And later on in data I have:
`phoneMask: {
        mask() {
          return ['999-999-999[9]', '9{11,}'];
        }}`

I also tried more direct:
`phoneMask: {  mask: ['999-999-999[999]', '9{11,}'] }`

It looks like it always filters with first mask only. I had an old code and more manual binding - than it was working with both masks, but there were other formatting issues (note important in this case).
Am I doing something wrong?

**Comment by mariuszniemiec** [comment]
Maybe it's related to https://github.com/scleriot/vue-inputmask/issues/12 ?

**Comment by zyxd** [comment]
I [forked](https://github.com/syncraft/vue-inputmask-ng) this project and there's no problem with it (if i understand the issue correctly).

https://jsfiddle.net/2mrvxp98

**Comment by mariuszniemiec** [comment]
Sorry for very late response @zyxd 
I agree this works in general, but as far as I remmember I had more of a business logic issue more than technical. I was able to adjust it in some other way.
Thanks for response I'm closing this issue.
